### ISSUE TITLE
Program Hangs When Trezor Connected via USB Hub

### ISSUE THREAD

**Issue by woodydeck** [hiviah/TrezorPass#2]
Using a Macbook Pro 2015, the program will not work unless the Trezor is plugged directly into the native socket. Tried with a few hubs, USB 3.0 and USB 2.0. The Trezor plays nicely with MultiBit and MyTrezor via these hubs as well.

**Comment by hiviah** [comment]
Unfortunately, that's issue of underlying python-trezor USB HID layer which is known to have some quirks.

**Comment by woodydeck** [comment]
Thank you for that. I couldn't figure out the source of the issue, and I am glad it cannot be tied to hardware on my end. 

I am paranoid now after buyin two separate USB 3.0 enclosures that claimed to have UASP support, and instead the cheeky manufacturers in China put USB 2.0 controllers in the hardware thinking nobody would notice!
